# Generated by Django 6.0.6 on 2026-06-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_url', models.URLField(help_text='e.g. http://192.168.1.50:8473')),
                ('token', models.CharField(blank=True, help_text="the node's bearer token (`ara node token`)", max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('last_status', models.JSONField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
